### ISSUE TITLE
Common Dockerfile enhancement

### ISSUE THREAD

**Issue by mate-biro** [i-Cell-Mobilsoft-Open-Source/docker-wildfly#34]
`dockerfile/wildfly/common/Dockerfile` uses a `WILDFLY_PROPERTIES_FILE` environment variable which could have a default value, namely a `wildfly.empty.properties` (with empty content) to prevent implementing projects to define their own `empty.properties` file if no special configuration is needed for their built image.

At least this empty properties file is needed for the execution, otherwise the following command will fail:
`CMD exec "$WILDFLY_HOME/bin/standalone.sh" -P $WILDFLY_PROPERTIES_FILE -b 0.0.0.0 -bmanagement 0.0.0.0`

**Comment by cserhatit** [comment]
dockerfile touches the file, you dont need to define own empty properties. Optionally you can overwrite the default empty wildfly properties (see the wildfly.properties.file label in the docker image) with mounting a new one.
